# Generated by Django 4.0.4 on 2022-10-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classes.course'),
        ),
        migrations.AddField(
            model_name='slide',
            name='lecture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.lecture'),
        ),
    ]
